### ISSUE TITLE
create API endpoint for dataspace summary

### ISSUE THREAD

**Issue by tgbugs** [NeuroscienceKnowledgeSpace/KnowledgeSpace#26]
Endpoint should accept a curie (or a search term? @samuel-kerrien can you issue queries using the MBA:1234 curies directly from the atlases?). For example https://knowledge-space.org/api/dataspace/summary/ILX:1234567. And return the following json: ```{'category1':  
    {'source1':{'count':12345,  
                      'link':'http://mydata#dataspace.source',  
                      'description':'mydescription'  
                     }  
    },  
 'category2':{...},  
}```

This is essentially an APIification of https://github.com/NeuroscienceKnowledgeSpace/KnowledgeSpace/blob/master/NeuroKS/application/controllers/Pages.php#L56
Can be computed once a week and cache evicted when sources update (or something like that).

**Comment by wawong** [comment]
The NIF services are not stable today due to the SDSC network outage. I implemented a version and deployed it to kaa. See kaa.neuinfo.org/NeuroKS/index.php/API/summary/UBERON:0001950

I have couple questions. 1) Does the URL format matter to you? It's much easier to reuse the same context name and existing code. 2) What should the parameter, "link", contain? Currently, it makes no difference between /NeuroKS/index.php/pages/view/UBERON:0001950 and /NeuroKS/index.php/pages/view/UBERON:0001950#dataspace.

**Comment by samuel-kerrien** [comment]
To answer to point 2:
The link is a URL back to the KnowledgeSpace website that would render the
list of items of that specific category. This option is preferable to us
hard coding the URL in our application so that you can evolve your website
without us having to know it.

Cheers
Sam

**Comment by wawong** [comment]
Tom, I'm going to

**Comment by wawong** [comment]
Hi Sam,

Please take a look at this URL and let me know whether it meets your requirements:
http://kaa.neuinfo.org/NeuroKS/index.php/API/summary/UBERON:0001950

**Comment by samuel-kerrien** [comment]
Talking to Michael Dupont (Responsible for frontend of the Neuroinformatics
platform), it appears this is what we need.
He just would like to know if you could also add in the output of the API
call the links to an overview page for the term queried as well.
For instance, given this API call:
http://kaa.neuinfo.org/NeuroKS/index.php/API/summary/UBERON:0001950
Make sure this URL shows too:
https://knowledge-space.org/NeuroKS/index.php/pages/view/UBERON:0001950

Could you please also confirm that this will work with terms from the Allen
Mouse Brain Atlas ?

Cheers
Sam

**Comment by wawong** [comment]
I just added the new field, overview_url to the JSON result. Note that it is currently pointing to kaa. This URL will point to knowledge-space.org when I deploy the new version to the production server. 

I think the terms from ABA should work the same. Can you show me some test cases? So that, we can look into them.

**Comment by samuel-kerrien** [comment]
Thanks Willy,

I have now tried the following queries with the Allen Mouse Brain Atlas and I get the expected response:
http://kaa.neuinfo.org/NeuroKS/index.php/API/summary/MBA:59
http://kaa.neuinfo.org/NeuroKS/index.php/API/summary/MBA:129
http://kaa.neuinfo.org/NeuroKS/index.php/API/summary/MBA:354

Michael will check the API output again and get back to you if he has any more comments.

**Comment by mdupont** [comment]
Hi @wawong 

AFAICS everything I need is present in the JSON result, I give my 👍 

Cheers,
Michaël

**Comment by wawong** [comment]
I deployed the latest version to the production server. See https://knowledge-space.org/NeuroKS/index.php/API/summary/UBERON:0001950

Reopen the ticket if there is anything that you want to add.
