### ISSUE TITLE
Direct searches to a specific page if one exists

### ISSUE THREAD

**Issue by MBAbrams** [NeuroscienceKnowledgeSpace/KnowledgeSpace#27]

**Comment by tgbugs** [comment]
e.g. a search for 'spiny neuron' should redirect directly to https://knowledge-space.org/NeuroKS/index.php/pages/view/NIFNEURMOR:nlx_cell_100601 instead of https://knowledge-space.org/NeuroKS/index.php/Search becuase there is only a single result from the vocabulary term endpoint: http://matrix.neuinfo.org:9000/scigraph/vocabulary/term/spiny%20neuron?searchAcronyms=false&searchSynonyms=true&searchAbbreviations=false&limit=20

**Comment by wawong** [comment]
This feature has been added to the production server. See https://knowledge-space.org

**Comment by tgbugs** [comment]
can you make it so that it does not show the redirect message?

**Comment by jgrethe** [comment]
Hi Willy - we shouldn't show a re-direct message (it should immediately re-direct).  

Also, Mathew had an issue where the re-direct stalled.

**Comment by wawong** [comment]
I just deployed the latest version to the server. Matthew, can you verify whether the new version fixes the problem?  https://knowledge-space.org

**Comment by tgbugs** [comment]
Closing this as accomplished. Issues where there are 'bad' redirects have been included under the improved search results page and/or are ontology issues.
